LOGLEVEL_DEBUG = 1
LOGLEVEL_INFO = 2
LOGLEVEL_WARNING = 3
LOGLEVEL_ERROR = 4
LOGLEVEL_CRITICAL = 5


MESSAGE_TYPE_INFO = 1
MESSAGE_TYPE_ERROR = 2
MESSAGE_TYPE_CLIENT_CONNECTED = 3
MESSAGE_TYPE_RECEIVED_REQUEST = 4
MESSAGE_TYPE_SHUTTING_DOWN_SERVICE = 5
MESSAGE_TYPE_BAD_INPUT = 6
MESSAGE_TYPE_SENDING_RESULTS = 7